In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("datasets/family_suitability.csv")
df

,Bedrooms,Area Safety (0-10),Distance to School (km),Distance to Church (km),"Garden (0-No, 1-Yes)",House Age (Years),Family Suitability
0,4,2,4.78,3.29,0,27,Not Good for Family
1,4,4,3.54,3.88,0,21,Not Good for Family
2,1,9,1.54,1.02,1,8,"Yes, Good for Family"
3,5,1,4.22,3.16,0,21,Not Good for Family
4,1,8,1.56,1.33,1,7,Not Good for Family
...,...,...,...,...,...,...,...
95,2,9,0.76,0.53,1,5,"Yes, Good for Family"
96,4,1,3.56,3.35,0,23,Not Good for Family
97,1,9,1.05,1.96,1,4,"Yes, Good for Family"
98,1,9,0.61,0.75,1,1,"Yes, Good for Family"
99,5,2,3.10,4.06,0,29,Not Good for Family

In [4]:
df.shape

(100, 7)

In [5]:
df.columns

Index(['Bedrooms', 'Area Safety (0-10)', 'Distance to School (km)',
       'Distance to Church (km)', 'Garden (0-No, 1-Yes)', 'House Age (Years)',
       'Family Suitability'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Bedrooms                 100 non-null    int64
 1   Area Safety (0-10)       100 non-null    int64
 2   Distance to School (km)  100 non-null    float64
 3   Distance to Church (km)  100 non-null    float64
 4   Garden (0-No, 1-Yes)     100 non-null    int64
 5   House Age (Years)        100 non-null    int64
 6   Family Suitability       100 non-null    object
dtypes: float64(2), int64(4), object(1)
memory usage: 5.6+ KB

In [7]:
df.dtypes

Bedrooms                     int64
Area Safety (0-10)           int64
Distance to School (km)    float64
Distance to Church (km)    float64
Garden (0-No, 1-Yes)         int64
House Age (Years)            int64
Family Suitability          object
dtype: object

In [8]:
df.describe()

,Bedrooms,Area Safety (0-10),Distance to School (km),Distance to Church (km),"Garden (0-No, 1-Yes)",House Age (Years)
count,100.000000,100.000000,100.000000,100.000000,100.00,100.000000
mean,2.820000,5.710000,2.500900,2.488100,0.55,12.680000
std,1.671991,3.131124,1.492584,1.456179,0.50,9.448296
min,1.000000,1.000000,0.520000,0.520000,0.00,1.000000
25%,1.000000,3.000000,1.127500,1.120000,0.00,4.000000
50%,2.000000,6.000000,1.900000,1.915000,1.00,9.000000
75%,5.000000,9.000000,3.880000,3.865000,1.00,21.000000
max,5.000000,10.000000,4.990000,4.940000,1.00,29.000000

In [10]:
df.head()

,Bedrooms,Area Safety (0-10),Distance to School (km),Distance to Church (km),"Garden (0-No, 1-Yes)",House Age (Years),Family Suitability
0,4,2,4.78,3.29,0,27,Not Good for Family
1,4,4,3.54,3.88,0,21,Not Good for Family
2,1,9,1.54,1.02,1,8,"Yes, Good for Family"
3,5,1,4.22,3.16,0,21,Not Good for Family
4,1,8,1.56,1.33,1,7,Not Good for Family

In [12]:
df.tail()

,Bedrooms,Area Safety (0-10),Distance to School (km),Distance to Church (km),"Garden (0-No, 1-Yes)",House Age (Years),Family Suitability
95,2,9,0.76,0.53,1,5,"Yes, Good for Family"
96,4,1,3.56,3.35,0,23,Not Good for Family
97,1,9,1.05,1.96,1,4,"Yes, Good for Family"
98,1,9,0.61,0.75,1,1,"Yes, Good for Family"
99,5,2,3.10,4.06,0,29,Not Good for Family

In [13]:
df.head(20)

,Bedrooms,Area Safety (0-10),Distance to School (km),Distance to Church (km),"Garden (0-No, 1-Yes)",House Age (Years),Family Suitability
0,4,2,4.78,3.29,0,27,Not Good for Family
1,4,4,3.54,3.88,0,21,Not Good for Family
2,1,9,1.54,1.02,1,8,"Yes, Good for Family"
3,5,1,4.22,3.16,0,21,Not Good for Family
4,1,8,1.56,1.33,1,7,Not Good for Family
5,1,9,0.52,1.89,1,1,Not Good for Family
6,5,3,4.42,4.62,0,18,Not Good for Family
7,1,10,1.90,1.96,1,5,"Yes, Good for Family"
8,5,3,4.79,3.64,0,15,Not Good for Family
9,1,6,1.57,1.69,1,5,"Yes, Good for Family"
10,5,4,4.11,4.19,0,21,Not Good for Family
11,4,4,3.20,4.33,0,27,Not Good for Family
12,5,4,4.73,4.12,0,26,Not Good for Family
13,5,4,4.49,4.44,0,15,Not Good for Family
14,1,10,1.94,0.52,1,5,"Yes, Good for Family"
15,5,3,4.52,4.12,0,29,Not Good for Family
16,1,9,0.52,1.86,1,9,"Yes, Good for Family"
17,5,3,4.90,4.15,0,29,Not Good for Family
18,1,8,1.13,0.83,1,3,"Yes, Good for Family"
19,5,2,3.97,3.90,0,27,Not Good for Family

In [14]:
df.tail(40)

,Bedrooms,Area Safety (0-10),Distance to School (km),Distance to Church (km),"Garden (0-No, 1-Yes)",House Age (Years),Family Suitability
60,5,4,3.37,4.87,0,15,Not Good for Family
61,1,7,1.12,1.37,1,9,"Yes, Good for Family"
62,5,1,3.16,3.86,0,26,Not Good for Family
63,2,7,0.88,0.94,1,1,"Yes, Good for Family"
64,4,1,4.66,3.54,0,26,Not Good for Family
65,1,9,1.08,1.94,1,2,"Yes, Good for Family"
66,1,9,1.70,1.47,1,3,"Yes, Good for Family"
67,1,8,1.43,1.00,1,8,"Yes, Good for Family"
68,1,9,0.76,1.15,1,7,"Yes, Good for Family"
69,2,8,1.55,1.30,1,1,Not Good for Family
70,1,10,1.63,1.69,1,9,"Yes, Good for Family"
71,4,1,3.63,3.34,0,23,Not Good for Family
72,4,4,4.13,3.32,0,20,Not Good for Family
73,1,6,0.73,1.97,1,6,"Yes, Good for Family"
74,1,9,1.40,0.91,1,3,"Yes, Good for Family"
75,2,10,1.61,1.33,1,6,"Yes, Good for Family"
76,1,9,1.74,0.98,1,3,"Yes, Good for Family"
77,1,9,1.57,0.86,1,5,"Yes, Good for Family"
78,5,2,4.90,4.78,0,26,Not Good for Family
79,1,10,0.67,0.57,1,1,"Yes, Good for Family"
80,5,3,4.01,4.71,0,19,Not Good for Family
81,4,4,3.75,3.74,0,18,Not Good for Family
82,1,9,1.58,0.92,1,3,"Yes, Good for Family"
83,2,8,1.90,1.68,1,8,"Yes, Good for Family"
84,2,7,0.67,1.79,1,8,"Yes, Good for Family"
85,5,4,3.27,4.94,0,24,Not Good for Family
86,2,8,0.78,0.56,1,4,"Yes, Good for Family"
87,2,7,0.64,1.06,1,8,"Yes, Good for Family"
88,5,1,4.38,3.77,0,16,Not Good for Family
89,4,1,3.81,4.14,0,18,Not Good for Family
90,2,10,1.99,0.61,1,3,"Yes, Good for Family"
91,1,10,1.61,0.86,1,1,"Yes, Good for Family"
92,5,3,3.85,4.81,0,21,Not Good for Family
93,5,1,3.20,3.17,0,27,Not Good for Family
94,2,8,1.72,1.70,1,9,"Yes, Good for Family"
95,2,9,0.76,0.53,1,5,"Yes, Good for Family"
96,4,1,3.56,3.35,0,23,Not Good for Family
97,1,9,1.05,1.96,1,4,"Yes, Good for Family"
98,1,9,0.61,0.75,1,1,"Yes, Good for Family"
99,5,2,3.10,4.06,0,29,Not Good for Family

In [16]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
      ...
95    False
96    False
97    False
98    False
99    False
Length: 100, dtype: bool