In [1]:
#import pandas 
import pandas as pd

print(pd.__version__)

2.1.4

In [3]:
df=pd.read_csv("datasets/recipe.csv")
df

    Flour  Milk  Sugar  Butter  Egg  Baking Powder  Vanilla  Salt     Type
0      55    28      3       7    5              2        0     0   Muffin
1      47    24     12       6    9              1        0     0   Muffin
2      47    23     18       6    4              1        0     0   Muffin
3      45    11     17      17    8              1        0     0   Muffin
4      50    25     12       6    5              2        1     0   Muffin
5      55    27      3       7    5              2        1     0   Muffin
6      54    27      7       5    5              2        0     0   Muffin
7      47    26     10      10    4              1        0     0   Muffin
8      50    17     17       8    6              1        0     0   Muffin
9      50    17     17      11    4              1        0     0   Muffin
10     39     0     26      19   14              1        1     0  Cupcake
11     42    21     16      10    8              3        0     0  Cupcake
12     34    17     20      20    5              2        1     0  Cupcake
13     39    13     17      19   10              1        1     0  Cupcake
14     38    15     23      15    8              0        1     0  Cupcake
15     42    18     25       9    5              1        0     0  Cupcake
16     36    14     21      14   11              2        1     0  Cupcake
17     38    15     31       8    6              1        1     0  Cupcake
18     36    16     24      12    9              1        1     0  Cupcake
19     34    17     23      11   13              0        1     0  Cupcake
20     29     3     46       6    0             11        0     6    Scone
21     19     3     36       3   14              7       14     5    Scone
22     20     5     52       5   10              3        0     5    Scone
23     19     6     50       5    6             10        0     3    Scone
24     19    10     51       5    0             10        0     5    Scone
25     55    28      3       7    5              2        0     0   Muffin
26     47    24     12       6    9              1        0     0   Muffin
27     47    23     18       6    4              1        0     0   Muffin
28     45    11     17      17    8              1        0     0   Muffin
29     50    25     12       6    5              2        1     0   Muffin
30     55    27      3       7    5              2        1     0   Muffin
31     54    27      7       5    5              2        0     0   Muffin
32     48    26     10      10    4              1        0     0   Muffin
33     50    17     17       8    6              1        0     0   Muffin
34     50    17     17      11    4              1        0     0   Muffin
35     38     0     26      19   14              1        1     0  Cupcake
36     42    21     16      10    8              3        0     0  Cupcake
37     34    17     20      20    5              2        1     0  Cupcake
38     39    13     17      18   10              1        1     0  Cupcake
39     38    15     23      15    8              0        1     0  Cupcake
40     41    18     25       9    5              1        0     0  Cupcake
41     36    14     21      14   11              2        1     0  Cupcake
42     38    15     31       8    6              1        1     0  Cupcake
43     36    16     24      12    9              1        1     0  Cupcake
44     34    17     23      11   12              0        1     0  Cupcake
45     29     3     46       6    0             11        0     6    Scone
46     19     3     36       3   14              7       14     5    Scone
47     20     5     52       5   10              3        0     5    Scone
48     19     6     50       5    6             10        0     3    Scone
49     19    10     51       5    0             10        0     5    Scone

In [4]:
#checking colums
df.columns

Index(['Flour', 'Milk', 'Sugar', 'Butter', 'Egg', 'Baking Powder', 'Vanilla',
       'Salt', 'Type'],
      dtype='object')

In [5]:
#checking the number of rows and columns
df.shape

(50, 9)

In [7]:
#information about the data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Flour          50 non-null     int64
 1   Milk           50 non-null     int64
 2   Sugar          50 non-null     int64
 3   Butter         50 non-null     int64
 4   Egg            50 non-null     int64
 5   Baking Powder  50 non-null     int64
 6   Vanilla        50 non-null     int64
 7   Salt           50 non-null     int64
 8   Type           50 non-null     object
dtypes: int64(8), object(1)
memory usage: 3.6+ KB

In [8]:
df.dtypes

Flour             int64
Milk              int64
Sugar             int64
Butter            int64
Egg               int64
Baking Powder     int64
Vanilla           int64
Salt              int64
Type             object
dtype: object

In [9]:
#describing data
df.describe()

,Flour,Milk,Sugar,Butter,Egg,Baking Powder,Vanilla,Salt
count,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000
mean,39.340000,15.920000,23.080000,9.740000,6.940000,2.680000,0.960000,0.960000
std,11.213348,8.090912,14.037617,4.898188,3.644453,3.152194,2.732719,1.989359
min,19.000000,0.000000,3.000000,3.000000,0.000000,0.000000,0.000000,0.000000
25%,34.000000,11.000000,16.000000,6.000000,5.000000,1.000000,0.000000,0.000000
50%,39.000000,17.000000,20.000000,8.000000,6.000000,1.000000,0.000000,0.000000
75%,47.750000,23.000000,26.000000,12.000000,9.000000,2.000000,1.000000,0.000000
max,55.000000,28.000000,52.000000,20.000000,14.000000,11.000000,14.000000,6.000000

In [10]:
#checking the first five rows
df.head()

   Flour  Milk  Sugar  Butter  Egg  Baking Powder  Vanilla  Salt    Type
0     55    28      3       7    5              2        0     0  Muffin
1     47    24     12       6    9              1        0     0  Muffin
2     47    23     18       6    4              1        0     0  Muffin
3     45    11     17      17    8              1        0     0  Muffin
4     50    25     12       6    5              2        1     0  Muffin

In [12]:
df.tail()

    Flour  Milk  Sugar  Butter  Egg  Baking Powder  Vanilla  Salt   Type
45     29     3     46       6    0             11        0     6  Scone
46     19     3     36       3   14              7       14     5  Scone
47     20     5     52       5   10              3        0     5  Scone
48     19     6     50       5    6             10        0     3  Scone
49     19    10     51       5    0             10        0     5  Scone

In [14]:
df.head(20)

    Flour  Milk  Sugar  Butter  Egg  Baking Powder  Vanilla  Salt     Type
0      55    28      3       7    5              2        0     0   Muffin
1      47    24     12       6    9              1        0     0   Muffin
2      47    23     18       6    4              1        0     0   Muffin
3      45    11     17      17    8              1        0     0   Muffin
4      50    25     12       6    5              2        1     0   Muffin
5      55    27      3       7    5              2        1     0   Muffin
6      54    27      7       5    5              2        0     0   Muffin
7      47    26     10      10    4              1        0     0   Muffin
8      50    17     17       8    6              1        0     0   Muffin
9      50    17     17      11    4              1        0     0   Muffin
10     39     0     26      19   14              1        1     0  Cupcake
11     42    21     16      10    8              3        0     0  Cupcake
12     34    17     20      20    5              2        1     0  Cupcake
13     39    13     17      19   10              1        1     0  Cupcake
14     38    15     23      15    8              0        1     0  Cupcake
15     42    18     25       9    5              1        0     0  Cupcake
16     36    14     21      14   11              2        1     0  Cupcake
17     38    15     31       8    6              1        1     0  Cupcake
18     36    16     24      12    9              1        1     0  Cupcake
19     34    17     23      11   13              0        1     0  Cupcake

In [15]:
df.tail(30)

    Flour  Milk  Sugar  Butter  Egg  Baking Powder  Vanilla  Salt     Type
20     29     3     46       6    0             11        0     6    Scone
21     19     3     36       3   14              7       14     5    Scone
22     20     5     52       5   10              3        0     5    Scone
23     19     6     50       5    6             10        0     3    Scone
24     19    10     51       5    0             10        0     5    Scone
25     55    28      3       7    5              2        0     0   Muffin
26     47    24     12       6    9              1        0     0   Muffin
27     47    23     18       6    4              1        0     0   Muffin
28     45    11     17      17    8              1        0     0   Muffin
29     50    25     12       6    5              2        1     0   Muffin
30     55    27      3       7    5              2        1     0   Muffin
31     54    27      7       5    5              2        0     0   Muffin
32     48    26     10      10    4              1        0     0   Muffin
33     50    17     17       8    6              1        0     0   Muffin
34     50    17     17      11    4              1        0     0   Muffin
35     38     0     26      19   14              1        1     0  Cupcake
36     42    21     16      10    8              3        0     0  Cupcake
37     34    17     20      20    5              2        1     0  Cupcake
38     39    13     17      18   10              1        1     0  Cupcake
39     38    15     23      15    8              0        1     0  Cupcake
40     41    18     25       9    5              1        0     0  Cupcake
41     36    14     21      14   11              2        1     0  Cupcake
42     38    15     31       8    6              1        1     0  Cupcake
43     36    16     24      12    9              1        1     0  Cupcake
44     34    17     23      11   12              0        1     0  Cupcake
45     29     3     46       6    0             11        0     6    Scone
46     19     3     36       3   14              7       14     5    Scone
47     20     5     52       5   10              3        0     5    Scone
48     19     6     50       5    6             10        0     3    Scone
49     19    10     51       5    0             10        0     5    Scone

In [17]:
#print specific columnc
df[["Flour","Milk"]]

    Flour  Milk
0      55    28
1      47    24
2      47    23
3      45    11
4      50    25
5      55    27
6      54    27
7      47    26
8      50    17
9      50    17
10     39     0
11     42    21
12     34    17
13     39    13
14     38    15
15     42    18
16     36    14
17     38    15
18     36    16
19     34    17
20     29     3
21     19     3
22     20     5
23     19     6
24     19    10
25     55    28
26     47    24
27     47    23
28     45    11
29     50    25
30     55    27
31     54    27
32     48    26
33     50    17
34     50    17
35     38     0
36     42    21
37     34    17
38     39    13
39     38    15
40     41    18
41     36    14
42     38    15
43     36    16
44     34    17
45     29     3
46     19     3
47     20     5
48     19     6
49     19    10

In [19]:
#check if data contains null values
df.isnull().sum()

Flour            0
Milk             0
Sugar            0
Butter           0
Egg              0
Baking Powder    0
Vanilla          0
Salt             0
Type             0
dtype: int64

In [ ]:
#checking duplicates
df.duplicated()
#shows duplicated data

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25     True
26     True
27     True
28     True
29     True
30     True
31     True
32    False
33     True
34     True
35    False
36     True
37     True
38    False
39     True
40    False
41     True
42     True
43     True
44    False
45     True
46     True
47     True
48     True
49     True
dtype: bool

In [21]:
#remove duplicates
df.drop_duplicates

<bound method DataFrame.drop_duplicates of     Flour  Milk  Sugar  Butter  Egg  Baking Powder  Vanilla  Salt     Type
0      55    28      3       7    5              2        0     0   Muffin
1      47    24     12       6    9              1        0     0   Muffin
2      47    23     18       6    4              1        0     0   Muffin
3      45    11     17      17    8              1        0     0   Muffin
4      50    25     12       6    5              2        1     0   Muffin
5      55    27      3       7    5              2        1     0   Muffin
6      54    27      7       5    5              2        0     0   Muffin
7      47    26     10      10    4              1        0     0   Muffin
8      50    17     17       8    6              1        0     0   Muffin
9      50    17     17      11    4              1        0     0   Muffin
10     39     0     26      19   14              1        1     0  Cupcake
11     42    21     16      10    8              3        0     0  Cupcake
12     34    17     20      20    5              2        1     0  Cupcake
13     39    13     17      19   10              1        1     0  Cupcake
14     38    15     23      15    8              0        1     0  Cupcake
15     42    18     25       9    5              1        0     0  Cupcake
16     36    14     21      14   11              2        1     0  Cupcake
17     38    15     31       8    6              1        1     0  Cupcake
18     36    16     24      12    9              1        1     0  Cupcake
19     34    17     23      11   13              0        1     0  Cupcake
20     29     3     46       6    0             11        0     6    Scone
21     19     3     36       3   14              7       14     5    Scone
22     20     5     52       5   10              3        0     5    Scone
23     19     6     50       5    6             10        0     3    Scone
24     19    10     51       5    0             10        0     5    Scone
25     55    28      3       7    5              2        0     0   Muffin
26     47    24     12       6    9              1        0     0   Muffin
27     47    23     18       6    4              1        0     0   Muffin
28     45    11     17      17    8              1        0     0   Muffin
29     50    25     12       6    5              2        1     0   Muffin
30     55    27      3       7    5              2        1     0   Muffin
31     54    27      7       5    5              2        0     0   Muffin
32     48    26     10      10    4              1        0     0   Muffin
33     50    17     17       8    6              1        0     0   Muffin
34     50    17     17      11    4              1        0     0   Muffin
35     38     0     26      19   14              1        1     0  Cupcake
36     42    21     16      10    8              3        0     0  Cupcake
37     34    17     20      20    5              2        1     0  Cupcake
38     39    13     17      18   10              1        1     0  Cupcake
39     38    15     23      15    8              0        1     0  Cupcake
40     41    18     25       9    5              1        0     0  Cupcake
41     36    14     21      14   11              2        1     0  Cupcake
42     38    15     31       8    6              1        1     0  Cupcake
43     36    16     24      12    9              1        1     0  Cupcake
44     34    17     23      11   12              0        1     0  Cupcake
45     29     3     46       6    0             11        0     6    Scone
46     19     3     36       3   14              7       14     5    Scone
47     20     5     52       5   10              3        0     5    Scone
48     19     6     50       5    6             10        0     3    Scone
49     19    10     51       5    0             10        0     5    Scone>