In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("datasets/BreadBasket.csv")
df

       Transaction           Item         date_time period_day weekday_weekend
0                1          Bread  30-10-2016 09:58    morning         weekend
1                2   Scandinavian  30-10-2016 10:05    morning         weekend
2                2   Scandinavian  30-10-2016 10:05    morning         weekend
3                3  Hot chocolate  30-10-2016 10:07    morning         weekend
4                3            Jam  30-10-2016 10:07    morning         weekend
...            ...            ...               ...        ...             ...
20502         9682         Coffee  09-04-2017 14:32  afternoon         weekend
20503         9682            Tea  09-04-2017 14:32  afternoon         weekend
20504         9683         Coffee  09-04-2017 14:57  afternoon         weekend
20505         9683         Pastry  09-04-2017 14:57  afternoon         weekend
20506         9684      Smoothies  09-04-2017 15:04  afternoon         weekend

[20507 rows x 5 columns]

In [3]:
df.columns

Index(['Transaction', 'Item', 'date_time', 'period_day', 'weekday_weekend'], dtype='object')

In [4]:
df.shape

(20507, 5)

In [5]:
df.dtypes

Transaction         int64
Item               object
date_time          object
period_day         object
weekday_weekend    object
dtype: object

In [6]:
df.head(10)

   Transaction           Item         date_time period_day weekday_weekend
0            1          Bread  30-10-2016 09:58    morning         weekend
1            2   Scandinavian  30-10-2016 10:05    morning         weekend
2            2   Scandinavian  30-10-2016 10:05    morning         weekend
3            3  Hot chocolate  30-10-2016 10:07    morning         weekend
4            3            Jam  30-10-2016 10:07    morning         weekend
5            3        Cookies  30-10-2016 10:07    morning         weekend
6            4         Muffin  30-10-2016 10:08    morning         weekend
7            5         Coffee  30-10-2016 10:13    morning         weekend
8            5         Pastry  30-10-2016 10:13    morning         weekend
9            5          Bread  30-10-2016 10:13    morning         weekend

In [7]:
df.tail(49)

,Transaction,Item,date_time,period_day,weekday_weekend
20458,9658,Spanish Brunch,09-04-2017 11:30,morning,weekend
20459,9658,Extra Salami or Feta,09-04-2017 11:30,morning,weekend
20460,9659,Tea,09-04-2017 11:31,morning,weekend
20461,9659,Juice,09-04-2017 11:31,morning,weekend
20462,9659,Cake,09-04-2017 11:31,morning,weekend
20463,9660,Bread,09-04-2017 11:34,morning,weekend
20464,9664,Coffee,09-04-2017 11:40,morning,weekend
20465,9664,Coffee,09-04-2017 11:40,morning,weekend
20466,9664,Bread,09-04-2017 11:40,morning,weekend
20467,9665,Coffee,09-04-2017 11:59,morning,weekend
20468,9665,Juice,09-04-2017 11:59,morning,weekend
20469,9665,Spanish Brunch,09-04-2017 11:59,morning,weekend
20470,9666,Coffee,09-04-2017 12:01,afternoon,weekend
20471,9667,Bread,09-04-2017 12:04,afternoon,weekend
20472,9667,Sandwich,09-04-2017 12:04,afternoon,weekend
20473,9667,Sandwich,09-04-2017 12:04,afternoon,weekend
20474,9668,Tea,09-04-2017 12:07,afternoon,weekend
20475,9668,Bread,09-04-2017 12:07,afternoon,weekend
20476,9669,Farm House,09-04-2017 12:15,afternoon,weekend
20477,9670,Farm House,09-04-2017 12:22,afternoon,weekend
20478,9671,Bread,09-04-2017 12:28,afternoon,weekend
20479,9672,Coffee,09-04-2017 12:31,afternoon,weekend
20480,9672,Cookies,09-04-2017 12:31,afternoon,weekend
20481,9672,Extra Salami or Feta,09-04-2017 12:31,afternoon,weekend
20482,9673,Spanish Brunch,09-04-2017 12:32,afternoon,weekend
20483,9673,Coffee,09-04-2017 12:32,afternoon,weekend
20484,9673,Bread,09-04-2017 12:32,afternoon,weekend
20485,9674,Coffee,09-04-2017 13:04,afternoon,weekend
20486,9676,Smoothies,09-04-2017 13:06,afternoon,weekend
20487,9676,Sandwich,09-04-2017 13:06,afternoon,weekend
20488,9677,Tacos/Fajita,09-04-2017 13:20,afternoon,weekend
20489,9677,Coke,09-04-2017 13:20,afternoon,weekend
20490,9678,Coffee,09-04-2017 13:49,afternoon,weekend
20491,9678,Tacos/Fajita,09-04-2017 13:49,afternoon,weekend
20492,9678,Toast,09-04-2017 13:49,afternoon,weekend
20493,9679,Bread,09-04-2017 14:08,afternoon,weekend
20494,9679,Spanish Brunch,09-04-2017 14:08,afternoon,weekend
20495,9680,Bread,09-04-2017 14:24,afternoon,weekend
20496,9681,Truffles,09-04-2017 14:30,afternoon,weekend
20497,9681,Tea,09-04-2017 14:30,afternoon,weekend
20498,9681,Spanish Brunch,09-04-2017 14:30,afternoon,weekend
20499,9681,Christmas common,09-04-2017 14:30,afternoon,weekend
20500,9682,Muffin,09-04-2017 14:32,afternoon,weekend
20501,9682,Tacos/Fajita,09-04-2017 14:32,afternoon,weekend
20502,9682,Coffee,09-04-2017 14:32,afternoon,weekend
20503,9682,Tea,09-04-2017 14:32,afternoon,weekend
20504,9683,Coffee,09-04-2017 14:57,afternoon,weekend
20505,9683,Pastry,09-04-2017 14:57,afternoon,weekend
20506,9684,Smoothies,09-04-2017 15:04,afternoon,weekend

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20507 entries, 0 to 20506
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Transaction      20507 non-null  int64
 1   Item             20507 non-null  object
 2   date_time        20507 non-null  object
 3   period_day       20507 non-null  object
 4   weekday_weekend  20507 non-null  object
dtypes: int64(1), object(4)
memory usage: 801.2+ KB

In [9]:
df.describe()

        Transaction
count  20507.000000
mean    4976.202370
std     2796.203001
min        1.000000
25%     2552.000000
50%     5137.000000
75%     7357.000000
max     9684.000000

In [10]:
df.isnull().sum()

Transaction        0
Item               0
date_time          0
period_day         0
weekday_weekend    0
dtype: int64

In [11]:
df.duplicated()

0        False
1        False
2         True
3        False
4        False
         ...
20502    False
20503    False
20504    False
20505    False
20506    False
Length: 20507, dtype: bool

In [12]:
df.drop(["Transaction","date_time"],axis=1,inplace=True)

In [13]:
df.isnull().sum()

Item               0
period_day         0
weekday_weekend    0
dtype: int64

In [14]:
df.to_csv("cleaned-BreadBasket.csv",index=False)
print("Exported successfully")

Exported successfully