In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("datasets/Cleaned-HotelBooking.csv")
df

,hotel,is_canceled,days_btwn_booked_and_reported,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,days_in_waiting_list,customer_type,Average_daily_rate,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,Year
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,94.138306,0,Transient,0.00,0,0,Check-Out,2015-07-01,2015
1,Resort Hotel,0,0,2015,July,27,1,0,0,2,...,No Deposit,94.138306,0,Transient,0.00,0,0,Check-Out,2015-07-01,2015
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,94.138306,0,Transient,75.00,0,0,Check-Out,2015-07-02,2015
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.000000,0,Transient,75.00,0,0,Check-Out,2015-07-02,2015
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.000000,0,Transient,98.00,0,1,Check-Out,2015-07-03,2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87365,City Hotel,0,23,2017,August,35,30,2,5,2,...,No Deposit,394.000000,0,Transient,96.14,0,0,Check-Out,2017-09-06,2017
87366,City Hotel,0,102,2017,August,35,31,2,5,3,...,No Deposit,9.000000,0,Transient,225.43,0,2,Check-Out,2017-09-07,2017
87367,City Hotel,0,34,2017,August,35,31,2,5,2,...,No Deposit,9.000000,0,Transient,157.71,0,4,Check-Out,2017-09-07,2017
87368,City Hotel,0,109,2017,August,35,31,2,5,2,...,No Deposit,89.000000,0,Transient,104.40,0,0,Check-Out,2017-09-07,2017
87369,City Hotel,0,205,2017,August,35,29,2,7,2,...,No Deposit,9.000000,0,Transient,151.20,0,2,Check-Out,2017-09-07,2017

In [4]:
df.columns

Index(['hotel', 'is_canceled', 'days_btwn_booked_and_reported',
       'arrival_date_year', 'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies', 'meal',
       'country', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'assigned_room_type', 'booking_changes', 'deposit_type', 'agent',
       'days_in_waiting_list', 'customer_type', 'Average_daily_rate',
       'required_car_parking_spaces', 'total_of_special_requests',
       'reservation_status', 'reservation_status_date', 'Year'],
      dtype='object')

In [5]:
df.shape

(87370, 32)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87370 entries, 0 to 87369
Data columns (total 32 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   hotel                           87370 non-null  object
 1   is_canceled                     87370 non-null  int64
 2   days_btwn_booked_and_reported   87370 non-null  int64
 3   arrival_date_year               87370 non-null  int64
 4   arrival_date_month              87370 non-null  object
 5   arrival_date_week_number        87370 non-null  int64
 6   arrival_date_day_of_month       87370 non-null  int64
 7   stays_in_weekend_nights         87370 non-null  int64
 8   stays_in_week_nights            87370 non-null  int64
 9   adults                          87370 non-null  int64
 10  children                        87370 non-null  float64
 11  babies                          87370 non-null  int64
 12  meal                            87370 non-null  object
 13  country                         87370 non-null  object
 14  market_segment                  87370 non-null  object
 15  distribution_channel            87370 non-null  object
 16  is_repeated_guest               87370 non-null  int64
 17  previous_cancellations          87370 non-null  int64
 18  previous_bookings_not_canceled  87370 non-null  int64
 19  reserved_room_type              87370 non-null  object
 20  assigned_room_type              87370 non-null  object
 21  booking_changes                 87370 non-null  int64
 22  deposit_type                    87370 non-null  object
 23  agent                           87370 non-null  float64
 24  days_in_waiting_list            87370 non-null  int64
 25  customer_type                   87370 non-null  object
 26  Average_daily_rate              87370 non-null  float64
 27  required_car_parking_spaces     87370 non-null  int64
 28  total_of_special_requests       87370 non-null  int64
 29  reservation_status              87370 non-null  object
 30  reservation_status_date         87370 non-null  object
 31  Year                            87370 non-null  int64
dtypes: float64(3), int64(17), object(12)
memory usage: 21.3+ MB

In [7]:
df.describe()

,is_canceled,days_btwn_booked_and_reported,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,agent,days_in_waiting_list,Average_daily_rate,required_car_parking_spaces,total_of_special_requests,Year
count,87370.000000,87370.000000,87370.000000,87370.000000,87370.000000,87370.000000,87370.000000,87370.000000,87370.000000,87370.000000,87370.000000,87370.000000,87370.000000,87370.000000,87370.000000,87370.000000,87370.000000,87370.000000,87370.000000,87370.000000
mean,0.274969,79.903251,2016.210290,26.839533,15.815360,1.005448,2.625798,1.875953,0.138675,0.010828,0.039087,0.030422,0.184045,0.271672,94.130434,0.749788,106.346935,0.084251,0.698638,2016.186929
std,0.446501,86.028178,0.686116,13.673204,8.834842,1.031974,2.053692,0.626473,0.455933,0.113613,0.193802,0.369200,1.732148,0.727335,104.997255,10.017213,55.004259,0.281571,0.831946,0.680334
min,0.000000,0.000000,2015.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,-6.380000,0.000000,0.000000,2014.000000
25%,0.000000,11.000000,2016.000000,16.000000,8.000000,0.000000,1.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,9.000000,0.000000,72.000000,0.000000,0.000000,2016.000000
50%,0.000000,49.000000,2016.000000,27.000000,16.000000,1.000000,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,28.000000,0.000000,98.100000,0.000000,0.000000,2016.000000
75%,1.000000,125.000000,2017.000000,37.000000,23.000000,2.000000,4.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,234.000000,0.000000,134.000000,0.000000,1.000000,2017.000000
max,1.000000,709.000000,2017.000000,53.000000,31.000000,19.000000,50.000000,55.000000,10.000000,10.000000,1.000000,26.000000,72.000000,21.000000,535.000000,391.000000,5400.000000,8.000000,5.000000,2017.000000

In [8]:
df.dtypes

hotel                              object
is_canceled                         int64
days_btwn_booked_and_reported       int64
arrival_date_year                   int64
arrival_date_month                 object
arrival_date_week_number            int64
arrival_date_day_of_month           int64
stays_in_weekend_nights             int64
stays_in_week_nights                int64
adults                              int64
children                          float64
babies                              int64
meal                               object
country                            object
market_segment                     object
distribution_channel               object
is_repeated_guest                   int64
previous_cancellations              int64
previous_bookings_not_canceled      int64
reserved_room_type                 object
assigned_room_type                 object
booking_changes                     int64
deposit_type                       object
agent                             float64
days_in_waiting_list                int64
customer_type                      object
Average_daily_rate                float64
required_car_parking_spaces         int64
total_of_special_requests           int64
reservation_status                 object
reservation_status_date            object
Year                                int64
dtype: object

In [9]:
df.isnull().sum()

hotel                             0
is_canceled                       0
days_btwn_booked_and_reported     0
arrival_date_year                 0
arrival_date_month                0
arrival_date_week_number          0
arrival_date_day_of_month         0
stays_in_weekend_nights           0
stays_in_week_nights              0
adults                            0
children                          0
babies                            0
meal                              0
country                           0
market_segment                    0
distribution_channel              0
is_repeated_guest                 0
previous_cancellations            0
previous_bookings_not_canceled    0
reserved_room_type                0
assigned_room_type                0
booking_changes                   0
deposit_type                      0
agent                             0
days_in_waiting_list              0
customer_type                     0
Average_daily_rate                0
required_car_parking_spaces       0
total_of_special_requests         0
reservation_status                0
reservation_status_date           0
Year                              0
dtype: int64

In [10]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
87365    False
87366    False
87367    False
87368    False
87369    False
Length: 87370, dtype: bool

In [11]:
df.head()

,hotel,is_canceled,days_btwn_booked_and_reported,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,days_in_waiting_list,customer_type,Average_daily_rate,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,Year
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,94.138306,0,Transient,0.0,0,0,Check-Out,2015-07-01,2015
1,Resort Hotel,0,0,2015,July,27,1,0,0,2,...,No Deposit,94.138306,0,Transient,0.0,0,0,Check-Out,2015-07-01,2015
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,94.138306,0,Transient,75.0,0,0,Check-Out,2015-07-02,2015
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.000000,0,Transient,75.0,0,0,Check-Out,2015-07-02,2015
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.000000,0,Transient,98.0,0,1,Check-Out,2015-07-03,2015

In [12]:
df.tail()

,hotel,is_canceled,days_btwn_booked_and_reported,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,days_in_waiting_list,customer_type,Average_daily_rate,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,Year
87365,City Hotel,0,23,2017,August,35,30,2,5,2,...,No Deposit,394.0,0,Transient,96.14,0,0,Check-Out,2017-09-06,2017
87366,City Hotel,0,102,2017,August,35,31,2,5,3,...,No Deposit,9.0,0,Transient,225.43,0,2,Check-Out,2017-09-07,2017
87367,City Hotel,0,34,2017,August,35,31,2,5,2,...,No Deposit,9.0,0,Transient,157.71,0,4,Check-Out,2017-09-07,2017
87368,City Hotel,0,109,2017,August,35,31,2,5,2,...,No Deposit,89.0,0,Transient,104.40,0,0,Check-Out,2017-09-07,2017
87369,City Hotel,0,205,2017,August,35,29,2,7,2,...,No Deposit,9.0,0,Transient,151.20,0,2,Check-Out,2017-09-07,2017