In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("datasets/Cluster5.csv")
df

    Unnamed: 0  Gender  Age  Annual Income  Spending Score  no
0           43       0   31      39.000000       61.000000   5
1           47       0   27      40.000000       47.000000   5
2           48       0   29      40.000000       42.000000   5
3           49       0   31      40.000000       42.000000   5
4           51       1   33      42.000000       60.000000   5
5           52       0   31      43.000000       54.000000   5
6           58       0   27      46.000000       51.000000   5
7           61       1   19      46.000000       55.000000   5
8           65       1   18      48.000000       59.000000   5
9           68       1   19      48.000000       59.000000   5
10          69       0   32      48.000000       47.000000   5
11          75       1   26      54.000000       54.000000   5
12          77       1   40      54.000000       48.000000   5
13          78       0   23      54.000000       52.000000   5
14          81       1   38      54.000000       55.000000   5
15          84       0   21      54.000000       57.000000   5
16          87       0   22      57.000000       55.000000   5
17          88       0   34      58.000000       60.000000   5
18          91       1   18      59.000000       41.000000   5
19          93       0   40      60.000000       40.000000   5
20          94       0   32      60.000000       42.000000   5
21          95       1   24      60.000000       52.000000   5
22          97       0   27      60.000000       50.000000   5
23          99       1   20      61.000000       49.000000   5
24         100       0   23      62.000000       41.000000   5
25         103       1   26      62.000000       55.000000   5
26         105       0   21      62.000000       42.000000   5
27         111       0   19      63.000000       54.000000   5
28         112       0   38      64.000000       42.000000   5
29         113       1   19      64.000000       46.000000   5
30         114       0   18      65.000000       48.000000   5
31         115       0   19      65.000000       50.000000   5
32         120       1   27      67.000000       56.000000   5
33         121       0   38      67.000000       40.000000   5
34         122       0   40      69.000000       58.000000   5
35         124       0   23      70.000000       29.000000   5
36         132       0   25      72.000000       34.000000   5
37         142       0   28      76.000000       40.000000   5
38         149       1   34      78.000000       50.324873   5
39         187       1   28      60.356784       68.000000   5

In [4]:
df.columns

Index(['Unnamed: 0', 'Gender', 'Age', 'Annual Income', 'Spending Score', 'no'], dtype='object')

In [5]:
df.shape

(40, 6)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      40 non-null     int64
 1   Gender          40 non-null     int64
 2   Age             40 non-null     int64
 3   Annual Income   40 non-null     float64
 4   Spending Score  40 non-null     float64
 5   no              40 non-null     int64
dtypes: float64(2), int64(4)
memory usage: 2.0 KB

In [7]:
df.describe()

       Unnamed: 0    Gender        Age  Annual Income  Spending Score    no
count   40.000000  40.00000  40.000000      40.000000       40.000000  40.0
mean    93.000000   0.37500  27.200000      57.283920       49.633122   5.0
std     31.590326   0.49029   6.940036      10.233233        8.211502   0.0
min     43.000000   0.00000  18.000000      39.000000       29.000000   5.0
25%     68.750000   0.00000  21.000000      48.000000       42.000000   5.0
50%     93.500000   0.00000  27.000000      60.000000       50.162437   5.0
75%    113.250000   1.00000  32.000000      64.000000       55.000000   5.0
max    187.000000   1.00000  40.000000      78.000000       68.000000   5.0

In [8]:
df.head()

   Unnamed: 0  Gender  Age  Annual Income  Spending Score  no
0          43       0   31           39.0            61.0   5
1          47       0   27           40.0            47.0   5
2          48       0   29           40.0            42.0   5
3          49       0   31           40.0            42.0   5
4          51       1   33           42.0            60.0   5

In [9]:
df.tail()

    Unnamed: 0  Gender  Age  Annual Income  Spending Score  no
35         124       0   23      70.000000       29.000000   5
36         132       0   25      72.000000       34.000000   5
37         142       0   28      76.000000       40.000000   5
38         149       1   34      78.000000       50.324873   5
39         187       1   28      60.356784       68.000000   5

In [10]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
dtype: bool

In [11]:
df.isnull().sum()

Unnamed: 0        0
Gender            0
Age               0
Annual Income     0
Spending Score    0
no                0
dtype: int64

In [12]:
df.dtypes

Unnamed: 0          int64
Gender              int64
Age                 int64
Annual Income     float64
Spending Score    float64
no                  int64
dtype: object

In [15]:
df.drop(["Unnamed: 0"],axis=1,inplace=True)

In [16]:
df

    Gender  Age  Annual Income  Spending Score  no
0        0   31      39.000000       61.000000   5
1        0   27      40.000000       47.000000   5
2        0   29      40.000000       42.000000   5
3        0   31      40.000000       42.000000   5
4        1   33      42.000000       60.000000   5
5        0   31      43.000000       54.000000   5
6        0   27      46.000000       51.000000   5
7        1   19      46.000000       55.000000   5
8        1   18      48.000000       59.000000   5
9        1   19      48.000000       59.000000   5
10       0   32      48.000000       47.000000   5
11       1   26      54.000000       54.000000   5
12       1   40      54.000000       48.000000   5
13       0   23      54.000000       52.000000   5
14       1   38      54.000000       55.000000   5
15       0   21      54.000000       57.000000   5
16       0   22      57.000000       55.000000   5
17       0   34      58.000000       60.000000   5
18       1   18      59.000000       41.000000   5
19       0   40      60.000000       40.000000   5
20       0   32      60.000000       42.000000   5
21       1   24      60.000000       52.000000   5
22       0   27      60.000000       50.000000   5
23       1   20      61.000000       49.000000   5
24       0   23      62.000000       41.000000   5
25       1   26      62.000000       55.000000   5
26       0   21      62.000000       42.000000   5
27       0   19      63.000000       54.000000   5
28       0   38      64.000000       42.000000   5
29       1   19      64.000000       46.000000   5
30       0   18      65.000000       48.000000   5
31       0   19      65.000000       50.000000   5
32       1   27      67.000000       56.000000   5
33       0   38      67.000000       40.000000   5
34       0   40      69.000000       58.000000   5
35       0   23      70.000000       29.000000   5
36       0   25      72.000000       34.000000   5
37       0   28      76.000000       40.000000   5
38       1   34      78.000000       50.324873   5
39       1   28      60.356784       68.000000   5