In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("datasets/movies.csv")
df

,movie_id,title,genres,description
0,1,The Great Escape Plan,Action Thriller,A team of specialists plots a daring breakout ...
1,2,Silent Orbit,Sci-Fi Drama,A lone astronaut drifts through space after lo...
2,3,Laughing Matters,Comedy,Two rival stand-up comedians are forced to sha...
3,4,Hearts in November,Romance Drama,Two strangers reconnect every autumn at the sa...
4,5,Shadow Protocol,Action Spy,An undercover agent must stop a rogue arms dea...
5,6,The Last Harvest,Drama,A farming family struggles to keep their land ...
6,7,Robo Rangers,Animation Family,A group of young inventors builds robot compan...
7,8,Midnight Static,Horror,A late-night radio host starts receiving broad...
8,9,Comic Con Chaos,Comedy,Convention volunteers scramble to fix a disast...
9,10,Galaxy Runners,Sci-Fi Action,A crew of smugglers races across the galaxy to...
10,11,The Wedding Detour,Comedy Romance,A cross-country road trip spirals out of contr...
11,12,Iron Harvest,Action Drama,A veteran returns home to fight corporate deve...
12,13,Whispering Pines,Horror Thriller,Campers uncover a decades-old secret buried be...
13,14,Second Chances Café,Drama Romance,A chef rebuilds her life and her business afte...
14,15,Cartoon Kingdom,Animation Family,A young princess teams up with talking forest ...
15,16,Quantum Heist,Sci-Fi Thriller,Scientists use experimental technology to pull...
16,17,Neighborhood Watch,Comedy,Suburban neighbors form an overzealous patrol ...
17,18,The Long Goodbye Tour,Drama Music,An aging rock star embarks on one final tour a...
18,19,Deep Current,Action Adventure,A salvage diver races rivals to recover treasu...
19,20,Letters from Yesterday,Romance Drama,A woman discovers a box of old love letters th...
20,21,Ghost Frequency,Horror,Paranormal investigators trace a haunting to a...
21,22,Pixel Pals,Animation Comedy,Video game characters come to life when the ar...
22,23,Skyline Uprising,Action Sci-Fi,Survivors fight back after machines take contr...
23,24,Coffee and Constellations,Romance Comedy,A barista and an astronomer keep colliding on ...
24,25,The Vanishing Point,Thriller,A detective chases a suspect who seems to disa...
25,26,Backyard Bandits,Comedy Family,Two rival kids run competing lemonade empires ...
26,27,Frostbite Station,Horror Sci-Fi,A remote arctic research team loses contact af...
27,28,The Understudy,Drama,A struggling actor gets one unexpected shot at...
28,29,Turbo Tumble,Animation Action,Racing snails compete in the biggest garden ch...
29,30,Harbor Lights,Romance Drama,A lighthouse keeper's quiet life changes when ...
30,31,Blackout City,Action Thriller,A blackout across the city becomes cover for a...
31,32,The Punchline,Comedy Drama,A comedy writer rediscovers his voice after a ...
32,33,Orbit Eleven,Sci-Fi Adventure,A space station crew must repair critical syst...
33,34,Cabin Fourteen,Horror,Friends on a weekend getaway realize the cabin...
34,35,The Recipe Box,Drama Family,A granddaughter follows a trail of recipes to ...
35,36,Circuit Breakers,Action Sci-Fi,Underground racers modify illegal tech to surv...
36,37,First Frost,Romance,Two rival ski instructors are forced to co-lea...
37,38,Static Kingdom,Animation Sci-Fi,Robot citizens must restore power to their cit...
38,39,The Alibi,Thriller Comedy,Two exes must pretend to be married to cover u...
39,40,Rivers End,Drama Adventure,A retired guide leads one last expedition down...

In [4]:
df.dtypes

movie_id        int64
title          object
genres         object
description    object
dtype: object

In [5]:
df.describe()

        movie_id
count  40.000000
mean   20.500000
std    11.690452
min     1.000000
25%    10.750000
50%    20.500000
75%    30.250000
max    40.000000

In [6]:
df.columns

Index(['movie_id', 'title', 'genres', 'description'], dtype='object')

In [7]:
df.shape

(40, 4)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   movie_id     40 non-null     int64
 1   title        40 non-null     object
 2   genres       40 non-null     object
 3   description  40 non-null     object
dtypes: int64(1), object(3)
memory usage: 1.4+ KB

In [9]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
dtype: bool

In [10]:
df.describe()

        movie_id
count  40.000000
mean   20.500000
std    11.690452
min     1.000000
25%    10.750000
50%    20.500000
75%    30.250000
max    40.000000

In [11]:
df.isnull().sum()

movie_id       0
title          0
genres         0
description    0
dtype: int64

In [12]:
df.drop(["movie_id"],axis=1,inplace=True)

In [13]:
df

,title,genres,description
0,The Great Escape Plan,Action Thriller,A team of specialists plots a daring breakout ...
1,Silent Orbit,Sci-Fi Drama,A lone astronaut drifts through space after lo...
2,Laughing Matters,Comedy,Two rival stand-up comedians are forced to sha...
3,Hearts in November,Romance Drama,Two strangers reconnect every autumn at the sa...
4,Shadow Protocol,Action Spy,An undercover agent must stop a rogue arms dea...
5,The Last Harvest,Drama,A farming family struggles to keep their land ...
6,Robo Rangers,Animation Family,A group of young inventors builds robot compan...
7,Midnight Static,Horror,A late-night radio host starts receiving broad...
8,Comic Con Chaos,Comedy,Convention volunteers scramble to fix a disast...
9,Galaxy Runners,Sci-Fi Action,A crew of smugglers races across the galaxy to...
10,The Wedding Detour,Comedy Romance,A cross-country road trip spirals out of contr...
11,Iron Harvest,Action Drama,A veteran returns home to fight corporate deve...
12,Whispering Pines,Horror Thriller,Campers uncover a decades-old secret buried be...
13,Second Chances Café,Drama Romance,A chef rebuilds her life and her business afte...
14,Cartoon Kingdom,Animation Family,A young princess teams up with talking forest ...
15,Quantum Heist,Sci-Fi Thriller,Scientists use experimental technology to pull...
16,Neighborhood Watch,Comedy,Suburban neighbors form an overzealous patrol ...
17,The Long Goodbye Tour,Drama Music,An aging rock star embarks on one final tour a...
18,Deep Current,Action Adventure,A salvage diver races rivals to recover treasu...
19,Letters from Yesterday,Romance Drama,A woman discovers a box of old love letters th...
20,Ghost Frequency,Horror,Paranormal investigators trace a haunting to a...
21,Pixel Pals,Animation Comedy,Video game characters come to life when the ar...
22,Skyline Uprising,Action Sci-Fi,Survivors fight back after machines take contr...
23,Coffee and Constellations,Romance Comedy,A barista and an astronomer keep colliding on ...
24,The Vanishing Point,Thriller,A detective chases a suspect who seems to disa...
25,Backyard Bandits,Comedy Family,Two rival kids run competing lemonade empires ...
26,Frostbite Station,Horror Sci-Fi,A remote arctic research team loses contact af...
27,The Understudy,Drama,A struggling actor gets one unexpected shot at...
28,Turbo Tumble,Animation Action,Racing snails compete in the biggest garden ch...
29,Harbor Lights,Romance Drama,A lighthouse keeper's quiet life changes when ...
30,Blackout City,Action Thriller,A blackout across the city becomes cover for a...
31,The Punchline,Comedy Drama,A comedy writer rediscovers his voice after a ...
32,Orbit Eleven,Sci-Fi Adventure,A space station crew must repair critical syst...
33,Cabin Fourteen,Horror,Friends on a weekend getaway realize the cabin...
34,The Recipe Box,Drama Family,A granddaughter follows a trail of recipes to ...
35,Circuit Breakers,Action Sci-Fi,Underground racers modify illegal tech to surv...
36,First Frost,Romance,Two rival ski instructors are forced to co-lea...
37,Static Kingdom,Animation Sci-Fi,Robot citizens must restore power to their cit...
38,The Alibi,Thriller Comedy,Two exes must pretend to be married to cover u...
39,Rivers End,Drama Adventure,A retired guide leads one last expedition down...

In [16]:
df.to_csv("cleaned-movies.csv",index=False)
print("Exported succesfully")

Exported succesfully