In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("datasets/Mall_Customers.csv")
df

     CustomerID  Gender  Age  Annual Income  Spending Score
0             1    Male   19           15.0            39.0
1             2    Male   21           15.0            81.0
2             3  Female   20           16.0             6.0
3             4  Female   23           16.0            77.0
4             5  Female   31           17.0            40.0
..          ...     ...  ...            ...             ...
195         196  Female   35          120.0            79.0
196         197  Female   45          126.0             NaN
197         198    Male   32          126.0            74.0
198         199    Male   32          137.0            18.0
199         200    Male   30          137.0            83.0

[200 rows x 5 columns]

In [4]:
df.dtypes

CustomerID          int64
Gender             object
Age                 int64
Annual Income     float64
Spending Score    float64
dtype: object

In [5]:
df.columns

Index(['CustomerID', 'Gender', 'Age', 'Annual Income', 'Spending Score'], dtype='object')

In [6]:
df.shape

(200, 5)

In [7]:
df.head()

   CustomerID  Gender  Age  Annual Income  Spending Score
0           1    Male   19           15.0            39.0
1           2    Male   21           15.0            81.0
2           3  Female   20           16.0             6.0
3           4  Female   23           16.0            77.0
4           5  Female   31           17.0            40.0

In [8]:
df.tail()

     CustomerID  Gender  Age  Annual Income  Spending Score
195         196  Female   35          120.0            79.0
196         197  Female   45          126.0             NaN
197         198    Male   32          126.0            74.0
198         199    Male   32          137.0            18.0
199         200    Male   30          137.0            83.0

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   CustomerID      200 non-null    int64
 1   Gender          196 non-null    object
 2   Age             200 non-null    int64
 3   Annual Income   199 non-null    float64
 4   Spending Score  197 non-null    float64
dtypes: float64(2), int64(2), object(1)
memory usage: 7.9+ KB

In [10]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
195    False
196    False
197    False
198    False
199    False
Length: 200, dtype: bool

In [11]:
df.isnull().sum()

CustomerID        0
Gender            4
Age               0
Annual Income     1
Spending Score    3
dtype: int64

In [12]:
df.describe()

       CustomerID         Age  Annual Income  Spending Score
count  200.000000  200.000000     199.000000      197.000000
mean   100.500000   38.850000      60.356784       50.324873
std     57.879185   13.969007      26.172859       25.639097
min      1.000000   18.000000      15.000000        1.000000
25%     50.750000   28.750000      41.000000       35.000000
50%    100.500000   36.000000      61.000000       50.000000
75%    150.250000   49.000000      78.000000       73.000000
max    200.000000   70.000000     137.000000       99.000000

In [13]:
df["Gender"]=df["Gender"].map({"Male":0,"Female":1})

In [14]:
df

     CustomerID  Gender  Age  Annual Income  Spending Score
0             1     0.0   19           15.0            39.0
1             2     0.0   21           15.0            81.0
2             3     1.0   20           16.0             6.0
3             4     1.0   23           16.0            77.0
4             5     1.0   31           17.0            40.0
..          ...     ...  ...            ...             ...
195         196     1.0   35          120.0            79.0
196         197     1.0   45          126.0             NaN
197         198     0.0   32          126.0            74.0
198         199     0.0   32          137.0            18.0
199         200     0.0   30          137.0            83.0

[200 rows x 5 columns]

In [15]:
df.drop(["CustomerID"],axis=1,inplace=True)

In [16]:
df

     Gender  Age  Annual Income  Spending Score
0       0.0   19           15.0            39.0
1       0.0   21           15.0            81.0
2       1.0   20           16.0             6.0
3       1.0   23           16.0            77.0
4       1.0   31           17.0            40.0
..      ...  ...            ...             ...
195     1.0   35          120.0            79.0
196     1.0   45          126.0             NaN
197     0.0   32          126.0            74.0
198     0.0   32          137.0            18.0
199     0.0   30          137.0            83.0

[200 rows x 4 columns]

In [17]:
df.to_csv('cleaned-CustomersID',index=False)
print("Exported successfully")

Exported successfully