In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("datasets/pima_indians.csv")
df

,Number Children,Glucose,BloodPressure,SkinThickness,Insulin,BMI,Age,Outcome
0,6,148,72,35,0,33.6,50,Likely to Have Diabetes
1,1,85,66,29,0,26.6,31,No Diabetes
2,8,183,64,0,0,23.3,32,Likely to Have Diabetes
3,1,89,66,23,94,28.1,21,No Diabetes
4,0,137,40,35,168,43.1,33,Likely to Have Diabetes
...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,63,No Diabetes
764,2,122,70,27,0,36.8,27,No Diabetes
765,5,121,72,23,112,26.2,30,No Diabetes
766,1,126,60,0,0,30.1,47,Likely to Have Diabetes
767,1,93,70,31,0,30.4,23,No Diabetes

In [3]:
df.columns

Index(['Number Children', 'Glucose', 'BloodPressure', 'SkinThickness',
       'Insulin', 'BMI', 'Age', 'Outcome'],
      dtype='object')

In [4]:
df.shape

(768, 8)

In [5]:
df.dtypes

Number Children      int64
Glucose              int64
BloodPressure        int64
SkinThickness        int64
Insulin              int64
BMI                float64
Age                  int64
Outcome             object
dtype: object

In [6]:
df.head()

,Number Children,Glucose,BloodPressure,SkinThickness,Insulin,BMI,Age,Outcome
0,6,148,72,35,0,33.6,50,Likely to Have Diabetes
1,1,85,66,29,0,26.6,31,No Diabetes
2,8,183,64,0,0,23.3,32,Likely to Have Diabetes
3,1,89,66,23,94,28.1,21,No Diabetes
4,0,137,40,35,168,43.1,33,Likely to Have Diabetes

In [7]:
df.tail()

,Number Children,Glucose,BloodPressure,SkinThickness,Insulin,BMI,Age,Outcome
763,10,101,76,48,180,32.9,63,No Diabetes
764,2,122,70,27,0,36.8,27,No Diabetes
765,5,121,72,23,112,26.2,30,No Diabetes
766,1,126,60,0,0,30.1,47,Likely to Have Diabetes
767,1,93,70,31,0,30.4,23,No Diabetes

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Number Children  768 non-null    int64
 1   Glucose          768 non-null    int64
 2   BloodPressure    768 non-null    int64
 3   SkinThickness    768 non-null    int64
 4   Insulin          768 non-null    int64
 5   BMI              768 non-null    float64
 6   Age              768 non-null    int64
 7   Outcome          768 non-null    object
dtypes: float64(1), int64(6), object(1)
memory usage: 48.1+ KB

In [9]:
df.describe()

,Number Children,Glucose,BloodPressure,SkinThickness,Insulin,BMI,Age
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,33.240885
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,11.760232
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,21.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,24.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,29.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,41.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,81.000000

In [10]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
763    False
764    False
765    False
766    False
767    False
Length: 768, dtype: bool

In [11]:
df.isnull().sum()

Number Children    0
Glucose            0
BloodPressure      0
SkinThickness      0
Insulin            0
BMI                0
Age                0
Outcome            0
dtype: int64

In [12]:
df.rename(columns={"Number Children":"Number of Children"},inplace=True)

In [13]:
df

,Number of Children,Glucose,BloodPressure,SkinThickness,Insulin,BMI,Age,Outcome
0,6,148,72,35,0,33.6,50,Likely to Have Diabetes
1,1,85,66,29,0,26.6,31,No Diabetes
2,8,183,64,0,0,23.3,32,Likely to Have Diabetes
3,1,89,66,23,94,28.1,21,No Diabetes
4,0,137,40,35,168,43.1,33,Likely to Have Diabetes
...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,63,No Diabetes
764,2,122,70,27,0,36.8,27,No Diabetes
765,5,121,72,23,112,26.2,30,No Diabetes
766,1,126,60,0,0,30.1,47,Likely to Have Diabetes
767,1,93,70,31,0,30.4,23,No Diabetes