In [1]:
import pandas as pd

In [3]:
df=pd.read_csv("datasets/sales_orders.csv")
df

,OrderID,Region,Product,Category,Quantity,UnitPrice,OrderDate,SalesPerson
0,O001,Nairobi,Laptop,Electronics,2,80000,2025-01-10,John
1,O002,Mombasa,Phone,Electronics,5,25000,2025-01-11,Mary
2,O003,Kisumu,Tablet,Electronics,3,35000,2025-01-12,Peter
3,O004,Nakuru,Laptop,Electronics,1,80000,2025-01-13,Susan
4,O005,Nairobi,Headphones,Accessories,10,3000,2025-01-14,David
5,O006,Mombasa,Phone,Electronics,4,25000,2025-01-15,Grace
6,O007,Kisumu,Mouse,Accessories,15,1500,2025-01-16,James
7,O008,Nakuru,Keyboard,Accessories,8,2500,2025-01-17,Faith
8,O009,Nairobi,Tablet,Electronics,2,35000,2025-01-18,Brian
9,O010,Mombasa,Laptop,Electronics,3,80000,2025-01-19,Ann

In [4]:
df.columns

Index(['OrderID', 'Region', 'Product', 'Category', 'Quantity', 'UnitPrice',
       'OrderDate', 'SalesPerson'],
      dtype='object')

In [5]:
df.shape

(10, 8)

In [6]:
df.dtypes

OrderID        object
Region         object
Product        object
Category       object
Quantity        int64
UnitPrice       int64
OrderDate      object
SalesPerson    object
dtype: object

In [7]:
df.head()

,OrderID,Region,Product,Category,Quantity,UnitPrice,OrderDate,SalesPerson
0,O001,Nairobi,Laptop,Electronics,2,80000,2025-01-10,John
1,O002,Mombasa,Phone,Electronics,5,25000,2025-01-11,Mary
2,O003,Kisumu,Tablet,Electronics,3,35000,2025-01-12,Peter
3,O004,Nakuru,Laptop,Electronics,1,80000,2025-01-13,Susan
4,O005,Nairobi,Headphones,Accessories,10,3000,2025-01-14,David

In [8]:
df.tail()

,OrderID,Region,Product,Category,Quantity,UnitPrice,OrderDate,SalesPerson
5,O006,Mombasa,Phone,Electronics,4,25000,2025-01-15,Grace
6,O007,Kisumu,Mouse,Accessories,15,1500,2025-01-16,James
7,O008,Nakuru,Keyboard,Accessories,8,2500,2025-01-17,Faith
8,O009,Nairobi,Tablet,Electronics,2,35000,2025-01-18,Brian
9,O010,Mombasa,Laptop,Electronics,3,80000,2025-01-19,Ann

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   OrderID      10 non-null     object
 1   Region       10 non-null     object
 2   Product      10 non-null     object
 3   Category     10 non-null     object
 4   Quantity     10 non-null     int64
 5   UnitPrice    10 non-null     int64
 6   OrderDate    10 non-null     object
 7   SalesPerson  10 non-null     object
dtypes: int64(2), object(6)
memory usage: 772.0+ bytes

In [10]:
df.describe()

        Quantity     UnitPrice
count  10.000000     10.000000
mean    5.300000  36700.000000
std     4.423423  32401.303129
min     1.000000   1500.000000
25%     2.250000   8500.000000
50%     3.500000  30000.000000
75%     7.250000  68750.000000
max    15.000000  80000.000000

In [11]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [12]:
df.isnull().sum()

OrderID        0
Region         0
Product        0
Category       0
Quantity       0
UnitPrice      0
OrderDate      0
SalesPerson    0
dtype: int64

In [13]:
df.drop(["OrderID"],axis=1,inplace=True)

In [14]:
df

,Region,Product,Category,Quantity,UnitPrice,OrderDate,SalesPerson
0,Nairobi,Laptop,Electronics,2,80000,2025-01-10,John
1,Mombasa,Phone,Electronics,5,25000,2025-01-11,Mary
2,Kisumu,Tablet,Electronics,3,35000,2025-01-12,Peter
3,Nakuru,Laptop,Electronics,1,80000,2025-01-13,Susan
4,Nairobi,Headphones,Accessories,10,3000,2025-01-14,David
5,Mombasa,Phone,Electronics,4,25000,2025-01-15,Grace
6,Kisumu,Mouse,Accessories,15,1500,2025-01-16,James
7,Nakuru,Keyboard,Accessories,8,2500,2025-01-17,Faith
8,Nairobi,Tablet,Electronics,2,35000,2025-01-18,Brian
9,Mombasa,Laptop,Electronics,3,80000,2025-01-19,Ann