In [33]:
import pandas as pd

In [34]:
df=pd.read_csv("datasets/students.csv")
df

   StudentID     Name  Gender  Age            Department  Score        Date
0      ST001     John    Male   22          Data Science     85  2025-01-15
1      ST002     Mary  Female   24        Cyber Security     92  2025-01-16
2      ST003    Peter    Male   21  Software Engineering     78  2025-01-17
3      ST004    Susan  Female   23          Data Science     88  2025-01-18
4      ST005    David    Male   25            Networking     67  2025-01-19
..       ...      ...     ...  ...                   ...    ...         ...
95     ST096  Queenie  Female   20        Cyber Security     97  2025-04-20
96     ST097   Robert    Male   22  Software Engineering     82  2025-04-21
97     ST098   Sylvia  Female   23          Data Science     88  2025-04-22
98     ST099  Timothy    Male   24            Networking     71  2025-04-23
99     ST100  Vanessa  Female   21        Cyber Security     94  2025-04-24

[100 rows x 7 columns]

In [35]:
df.columns

Index(['StudentID', 'Name', 'Gender', 'Age', 'Department', 'Score', 'Date'], dtype='object')

In [36]:
df.shape

(100, 7)

In [37]:
df.dtypes

StudentID     object
Name          object
Gender        object
Age            int64
Department    object
Score          int64
Date          object
dtype: object

In [38]:
df.head()

  StudentID   Name  Gender  Age            Department  Score        Date
0     ST001   John    Male   22          Data Science     85  2025-01-15
1     ST002   Mary  Female   24        Cyber Security     92  2025-01-16
2     ST003  Peter    Male   21  Software Engineering     78  2025-01-17
3     ST004  Susan  Female   23          Data Science     88  2025-01-18
4     ST005  David    Male   25            Networking     67  2025-01-19

In [39]:
df.tail()

   StudentID     Name  Gender  Age            Department  Score        Date
95     ST096  Queenie  Female   20        Cyber Security     97  2025-04-20
96     ST097   Robert    Male   22  Software Engineering     82  2025-04-21
97     ST098   Sylvia  Female   23          Data Science     88  2025-04-22
98     ST099  Timothy    Male   24            Networking     71  2025-04-23
99     ST100  Vanessa  Female   21        Cyber Security     94  2025-04-24

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   StudentID   100 non-null    object
 1   Name        100 non-null    object
 2   Gender      100 non-null    object
 3   Age         100 non-null    int64
 4   Department  100 non-null    object
 5   Score       100 non-null    int64
 6   Date        100 non-null    object
dtypes: int64(2), object(5)
memory usage: 5.6+ KB

In [41]:
df.describe()

              Age       Score
count  100.000000  100.000000
mean    22.520000   83.020000
std      1.493961    8.628096
min     20.000000   67.000000
25%     21.000000   76.000000
50%     22.500000   84.500000
75%     24.000000   90.000000
max     25.000000   97.000000

In [42]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
      ...
95    False
96    False
97    False
98    False
99    False
Length: 100, dtype: bool

In [43]:
df.isnull().sum()

StudentID     0
Name          0
Gender        0
Age           0
Department    0
Score         0
Date          0
dtype: int64

In [44]:
df.drop(["StudentID","Date"],axis=1,inplace=True)

In [45]:
df

       Name  Gender  Age            Department  Score
0      John    Male   22          Data Science     85
1      Mary  Female   24        Cyber Security     92
2     Peter    Male   21  Software Engineering     78
3     Susan  Female   23          Data Science     88
4     David    Male   25            Networking     67
..      ...     ...  ...                   ...    ...
95  Queenie  Female   20        Cyber Security     97
96   Robert    Male   22  Software Engineering     82
97   Sylvia  Female   23          Data Science     88
98  Timothy    Male   24            Networking     71
99  Vanessa  Female   21        Cyber Security     94

[100 rows x 5 columns]

In [54]:
df["Gender"]=df["Gender"].map({"Male":0,"Female":1})